## NumPy
---

In [1]:
# Import NumPy

import numpy as np

In [2]:
# Checking NumPy Version

print(np.__version__)

1.26.4


In [3]:
# Creating a NumPy array

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np          #importnya gaharus ditulis terus, cukup sekali bisa
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# Use a tuple to create a NumPy array

import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


##### Task - Basic NumPy
---

In [6]:
np.version.version

'1.26.4'

In [7]:
#List

list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)
print("Array dari list:")
print(array_from_list)
print(type(array_from_list))

Array dari list:
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
# Tuple

tuple_data =(5, 6, 7, 8, 9)
array_from_tuple = np.array(tuple_data)
print("Array dari tuple :")
print(array_from_tuple)
print(type(array_from_tuple))

Array dari tuple :
[5 6 7 8 9]
<class 'numpy.ndarray'>


#### Dimension in Arrays
---
A dimension in arrays is one level of array depth (nested arrays)

In [9]:
# e-D Arrays

arr = np.array(42)

In [10]:
# Create a 1-D array

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [11]:
# Create a 2-D array containing two arrays

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# Create a 3-D array with two 2-D arrays, both containing two arrays

arr = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3],[4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
# Check how many dimension the arrays have

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3],[4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


##### Task - Dimension
---

In [16]:
# 1Dimension

arr_1 = np.array([1, 2, 3, 4, 5])
print(arr_1)
print(arr_1.ndim)

[1 2 3 4 5]
1


In [17]:
# 2Dimension

arr_2 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print(arr_2)
print(arr_2.ndim)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
2


In [18]:
# 3Dimension

arr_3 = np.array([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]])
print(arr_3)
print(arr_3.ndim)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
3


In [19]:
# Create an array with 5 dimension and verify that it has 5 dimensions

import numpy as np
arr_1 = np.array([1, 2, 3, 4, 5], ndmin=5)
print(arr_1)
print('number of dimension:', arr_1.ndim)
print(arr_1[0])

[[[[[1 2 3 4 5]]]]]
number of dimension: 5
[[[[1 2 3 4 5]]]]


In [20]:
# Get the first element from the following array

arr = np.array([1, 2, 3, 4, 5])
print(arr[0])

1


In [21]:
# Get the second element from the following array

arr = np.array([1, 2, 3, 4, 5])
print(arr[1])

2


In [22]:
# Get the third and fourth element from the following array and add them

arr = np.array([1, 2, 3, 4, 5])
print(arr[2] + arr[3])

7


##### Task
---

In [27]:
# access the element on the first row, second column

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("2nd element on 1st row: ", arr[0,1])    #{row, elemen}

2nd element on 1st row:  2


In [28]:
# access the element on the 2nd row, 5th column

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("5th element on 2nd row: ", arr[1,4])

5th element on 2nd row:  10


In [29]:
#access the third element of the second array of the first array

arr = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
print(arr[1, 0, 2])    #[dim, row, elemen]

9


##### Task
---