## ***Pandas - Series***
---
---

import the libraries that will be needed

In [1]:
import pandas as pd
import numpy as np

Pandas has two objects, namely series and data frames

### Series
---
Series has one data dimension, does not have column names because it only has one column, and has an index

In [2]:
data = [0.25, 0.50, 0.75, 1]

In [3]:
print(data)

[0.25, 0.5, 0.75, 1]


In [11]:
data = pd.Series(data)

In [12]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [13]:
# Convert from series to array

##### Convert from series to array

In [14]:
data = [0.25, 0.50, 0.75, 1]

In [15]:
data = pd.Series(data)

In [16]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [17]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

##### Displays Index
---

The index is in the form of a range, where the start point is inclusive of the range and the stop point is exclusive of the range

In [18]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [19]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Calling data

In [20]:
data[2]      #indeksnya memakai indeks python

0.75

When defining Indexes, the number of indexes must be equal to the number of data

In [21]:
data = pd.Series([0.25, 0.50, 0.75, 1], index = ['a','b','c','d'])

In [22]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [23]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [24]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [25]:
# Indeks Eksplisit

data['a']

0.25

Because this is selection data, even though an explicit index has been created, the implicit index can still be called

In [26]:
# Indeks Implisit

data[2]

C:\Users\alifia\AppData\Local\Temp\ipykernel_19160\1719098127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data[2]


0.75

When the implicit and explicit indexes are the same, then when calling the data it will rely on the explicit index

In [27]:
data_2 = pd.Series([0.25, 0.5, 0.75, 1], index = [2, 5, 3, 7])

In [28]:
data_2[2]

0.25

In [29]:
data_2[0]

KeyError: 0

In [30]:
# Data slicing

data_2 = pd.Series([0.25, 0.5, 0.75, 1], index = ['a','b','c','d'])

In [31]:
data_2

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [32]:
# Memanggil dari data b sampai c

data_2['b': 'c']    #indeks eksplisit

b    0.50
c    0.75
dtype: float64

When slicing an implicit index, only the starting point will appear because the implicit index is a range

In [33]:
data_2[1 : 2]    #indeks implisit

b    0.5
dtype: float64

#### Loc - Iloc
---

In [34]:
data_2 = pd.Series([0.25, 0.5, 0.75, 1], index = [2, 5, 3, 7])

In [35]:
data_2

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

When we access an index, what appears is the explicit index

In [36]:
data_2[2]   #indeks eksplisit : selecting

0.25

When calling the explicit index from index 2 to 3, the value that appears is the implicit index

In [37]:
data_2[2:3]    #indeks implisit : slicing

3    0.75
dtype: float64

When the explicit and implicit indexes are the same, inconsistencies will occur, so loc and iloc are used

+ Loc to call an explicit index
+ Iloc to call implicit index

In [38]:
# Loc

data_2.loc[3]     #selecting index explicit

0.75

In [39]:
data_2.loc[2:3]   #slicing index explicit

2    0.25
5    0.50
3    0.75
dtype: float64

In [40]:
# Iloc

data_2.iloc[0]    #selecting index implisit

0.25

In [41]:
data_2.iloc[3]      #selecting index implisit

1.0

#### Task - Object Series
---

In [42]:
# Membuat Series dari Dictionary

data = {'a' : 10, 'b' : 20, 'c' : 30, 'd' : 40, 'e' : 50}

In [43]:
import pandas as pd
import numpy as np

In [44]:
print(data)

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}


In [45]:
series = pd.Series(data)
print(series)

a    10
b    20
c    30
d    40
e    50
dtype: int64


#### Task - Index 
---

In [46]:
data = [10, 20, 30, 40, 50]
series = pd.Series(data)

series

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [47]:
series.values

array([10, 20, 30, 40, 50], dtype=int64)

In [48]:
series.index

RangeIndex(start=0, stop=5, step=1)

In [49]:
list(range(1,3))

[1, 2]

In [50]:
series[4]

50

In [51]:
# Custom Index

data = [10, 20, 30, 40, 50]
index = ['a','b','c','d','e']
series_explicit_index = pd.Series(data, index=index)
print("Serie dengan indeks eksplisit: ")
print(series_explicit_index)

Serie dengan indeks eksplisit: 
a    10
b    20
c    30
d    40
e    50
dtype: int64


In [52]:
series_explicit_index['b']

20

In [53]:
series_explicit_index[2]

C:\Users\alifia\AppData\Local\Temp\ipykernel_19160\4047661461.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series_explicit_index[2]


30

#### Task
---

In [54]:
data = pd.Series([10, 20, 30, 40, 50], index = [3,2,1,4,5])
print(data)

3    10
2    20
1    30
4    40
5    50
dtype: int64


In [55]:
data[2]

20

In [56]:
data[0]

KeyError: 0

#### Task - Loc iloc
---

In [57]:
data = pd.Series([10, 20, 30, 40, 50], index = [3,2,1,4,5])
print(data)

3    10
2    20
1    30
4    40
5    50
dtype: int64


In [58]:
data.loc[4]

40

In [59]:
data.loc[2:4]

2    20
1    30
4    40
dtype: int64

In [60]:
data.iloc[2]

30

In [61]:
data = pd.Series([10, 20, 30, 40, 50], index = ['b','c','e','d','a'])

In [62]:
data

b    10
c    20
e    30
d    40
a    50
dtype: int64

In [63]:
data.loc['b']

10

In [64]:
data['b':'e']

b    10
c    20
e    30
dtype: int64

In [65]:
data.iloc[2]

30

In [66]:
data.iloc[1:3]

c    20
e    30
dtype: int64